services:
  - type: web
    name: pigeon-chat
    env: python
    buildCommand: "pip install -r requirements.txt & alembic upgrade head"
    startCommand: "python3 main.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pigeon-chat-db
          property: connectionString
    plan: free
    region: oregon

databases:
  - name: pigeon-chat-db
    plan: free
    region: oregon