services:
  - type: web
    name: pigeon-chat
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pigeon-chat-db
          property: connectionString
    plan: free
    region: oregon

databases:
  - name: pigeon-chat-db
    plan: free
    region: oregon